import "./globals.scss";

import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import {getCategories} from "@/lib/getCategories";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const categories = await getCategories(); 

  return (
    <html lang="en">
      <body>
        <Header categories={categories} />
        {children}
        <Footer categories={categories} />
      </body>
    </html>
  );
}
